### ISSUE TITLE
Auxiliary LAPACK routines?

### ISSUE THREAD

**Issue by SuperFluffy** [blas-lapack-rs/lapack#14]
What is your opinion on having LAPACK Auxiliary Routines in the crate, i.e. those listed here: http://www.netlib.org/lapack/lawn41/node112.html ?

I was looking at `_lassq` right now, and noticed that it's not part of this crate. Is this intentional, or do you welcome PRs for this?

**Comment by IvanUkhov** [comment]
The idea with this and related crates is to follow closely [`lapacke.h`](https://github.com/Reference-LAPACK/lapack/blob/master/LAPACKE/include/lapacke.h) by Netlib. If you need that auxiliary function, and it’s not in the header, I recommend defining it in your code and adding `lapack-sys` or `lapack` with an appropriate features activated in your dependencies; it should work.

**Comment by IvanUkhov** [comment]
It seems those auxiliary functions are provided not only in Netlib’s implementation but also in OpenBLAS, and one can also find them in Netlib’s [reference](http://www.netlib.org/lapack/explore-html/). Do you know if those functions are a part of the Fortran interface only or the C one too (LAPACKE)? It’d be nice to find a C header with those functions defined.

**Comment by SuperFluffy** [comment]
Sorry it took me so long to respond. I am not aware of any C header files which expose these functions. I have opened [an issue on the reference `LAPACK`](https://github.com/Reference-LAPACK/lapack/issues/115) to ask about this. :)

**Comment by IvanUkhov** [comment]
It seems the routines have been made available in 3.8.0 (November 2017).

I close this in favor of [`lapacke-sys/#1`](https://github.com/blas-lapack-rs/lapacke-sys/issues/1).
