### ISSUE TITLE
Add zrot

### ISSUE THREAD

**Issue by kevinsung** [blas-lapack-rs/lapack#30]
The zrot function seems to be missing.

https://www.netlib.org/lapack/explore-html/d0/d50/group__complex16_o_t_h_e_rauxiliary_ga423fa89faf02ec43f5b664f91ce29729.html#ga423fa89faf02ec43f5b664f91ce29729

**Comment by IvanUkhov** [comment]
Hello, it is not part of`lapack` but `blas`:

https://docs.rs/blas/latest/blas/

**Comment by kevinsung** [comment]
Very well. I opened https://github.com/blas-lapack-rs/blas/issues/43.
